In [1]:
#2.2.1创建NDArray

In [2]:
from mxnet import nd

In [3]:
x=nd.arange(12)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [4]:
x.shape

(12,)

In [5]:
x.size

12

In [6]:
X=x.reshape((3,4))
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [7]:
X=x.reshape((-1,4))
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [8]:
X=x.reshape((3,-1))
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [9]:
nd.zeros((2,3,4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [10]:
nd.ones((3,4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [11]:
Y = nd.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]) 
Y


[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
<NDArray 3x4 @cpu(0)>

In [12]:
# 每个元素都随机采样于均值为0、标准差为1的正态分布(normal)
nd.random.normal(0,1,shape=(3,4))


[[ 1.1630785   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.558071   -0.5459446  -2.3556297 ]
 [ 0.54144025  2.6785064   1.2546344  -0.54877406]]
<NDArray 3x4 @cpu(0)>

In [13]:
#2.2.2运算

In [14]:
X+Y,nd.elemwise_add(X,Y)#运算符全面函数elelwise_add()

(
 [[ 2.  2.  6.  6.]
  [ 5.  7.  9. 11.]
  [12. 12. 12. 12.]]
 <NDArray 3x4 @cpu(0)>,
 
 [[ 2.  2.  6.  6.]
  [ 5.  7.  9. 11.]
  [12. 12. 12. 12.]]
 <NDArray 3x4 @cpu(0)>)

In [15]:
X-Y,nd.elemwise_sub(X,Y)

(
 [[-2.  0. -2.  0.]
  [ 3.  3.  3.  3.]
  [ 4.  6.  8. 10.]]
 <NDArray 3x4 @cpu(0)>,
 
 [[-2.  0. -2.  0.]
  [ 3.  3.  3.  3.]
  [ 4.  6.  8. 10.]]
 <NDArray 3x4 @cpu(0)>)

In [16]:
X*Y,nd.elemwise_mul(X,Y)

(
 [[ 0.  1.  8.  9.]
  [ 4. 10. 18. 28.]
  [32. 27. 20. 11.]]
 <NDArray 3x4 @cpu(0)>,
 
 [[ 0.  1.  8.  9.]
  [ 4. 10. 18. 28.]
  [32. 27. 20. 11.]]
 <NDArray 3x4 @cpu(0)>)

In [17]:
X/Y,nd.elemwise_div(X,Y)

(
 [[ 0.    1.    0.5   1.  ]
  [ 4.    2.5   2.    1.75]
  [ 2.    3.    5.   11.  ]]
 <NDArray 3x4 @cpu(0)>,
 
 [[ 0.    1.    0.5   1.  ]
  [ 4.    2.5   2.    1.75]
  [ 2.    3.    5.   11.  ]]
 <NDArray 3x4 @cpu(0)>)

In [18]:
X,X**2

(
 [[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]
 <NDArray 3x4 @cpu(0)>,
 
 [[  0.   1.   4.   9.]
  [ 16.  25.  36.  49.]
  [ 64.  81. 100. 121.]]
 <NDArray 3x4 @cpu(0)>)

In [19]:
Y.exp(),nd.exp(Y)

(
 [[ 7.389056   2.7182817 54.59815   20.085537 ]
  [ 2.7182817  7.389056  20.085537  54.59815  ]
  [54.59815   20.085537   7.389056   2.7182817]]
 <NDArray 3x4 @cpu(0)>,
 
 [[ 7.389056   2.7182817 54.59815   20.085537 ]
  [ 2.7182817  7.389056  20.085537  54.59815  ]
  [54.59815   20.085537   7.389056   2.7182817]]
 <NDArray 3x4 @cpu(0)>)

In [20]:
#矩阵乘法dot，Y.T代表Y的转置
nd.dot(X,Y.T)


[[ 18.  20.  10.]
 [ 58.  60.  50.]
 [ 98. 100.  90.]]
<NDArray 3x3 @cpu(0)>

In [21]:
X,Y

(
 [[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]
 <NDArray 3x4 @cpu(0)>,
 
 [[2. 1. 4. 3.]
  [1. 2. 3. 4.]
  [4. 3. 2. 1.]]
 <NDArray 3x4 @cpu(0)>)

In [22]:
#按行连结两个矩阵
nd.concat(X, Y, dim=0)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 2.  1.  4.  3.]
 [ 1.  2.  3.  4.]
 [ 4.  3.  2.  1.]]
<NDArray 6x4 @cpu(0)>

In [23]:
#按列连结两个矩阵
nd.concat(X, Y, dim=1)


[[ 0.  1.  2.  3.  2.  1.  4.  3.]
 [ 4.  5.  6.  7.  1.  2.  3.  4.]
 [ 8.  9. 10. 11.  4.  3.  2.  1.]]
<NDArray 3x8 @cpu(0)>

In [24]:
#dim默认为1
nd.concat(X, Y)


[[ 0.  1.  2.  3.  2.  1.  4.  3.]
 [ 4.  5.  6.  7.  1.  2.  3.  4.]
 [ 8.  9. 10. 11.  4.  3.  2.  1.]]
<NDArray 3x8 @cpu(0)>

In [25]:
X==Y,X!=Y,X>Y,X<Y

(
 [[0. 1. 0. 1.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]
 <NDArray 3x4 @cpu(0)>,
 
 [[1. 0. 1. 0.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]
 <NDArray 3x4 @cpu(0)>,
 
 [[0. 0. 0. 0.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]
 <NDArray 3x4 @cpu(0)>,
 
 [[1. 0. 1. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]
 <NDArray 3x4 @cpu(0)>)

In [26]:
X.sum(),nd.sum(X)

(
 [66.]
 <NDArray 1 @cpu(0)>,
 
 [66.]
 <NDArray 1 @cpu(0)>)

In [27]:
X.norm(),nd.norm(X)

(
 [22.494442]
 <NDArray 1 @cpu(0)>,
 
 [22.494442]
 <NDArray 1 @cpu(0)>)

In [28]:
X.norm().asscalar()

22.494442

In [29]:
#2.2.3广播机制

In [30]:
A =nd.arange(3).reshape((3,1))
B =nd.arange(2).reshape((1,2))
A,B

(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>,
 
 [[0. 1.]]
 <NDArray 1x2 @cpu(0)>)

In [31]:
A+B


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

In [32]:
#2.2.4索引

In [33]:
X,Y

(
 [[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]
 <NDArray 3x4 @cpu(0)>,
 
 [[2. 1. 4. 3.]
  [1. 2. 3. 4.]
  [4. 3. 2. 1.]]
 <NDArray 3x4 @cpu(0)>)

In [34]:
X[1:3] , X[1:3,:] , X[1:3,1:3] ,

(
 [[ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]
 <NDArray 2x4 @cpu(0)>,
 
 [[ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]
 <NDArray 2x4 @cpu(0)>,
 
 [[ 5.  6.]
  [ 9. 10.]]
 <NDArray 2x2 @cpu(0)>)

In [35]:
X[1,2]=9
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  9.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [36]:
X[1:2]=11 
X


[[ 0.  1.  2.  3.]
 [11. 11. 11. 11.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [37]:
X[1:2,:]=12 
X


[[ 0.  1.  2.  3.]
 [12. 12. 12. 12.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [38]:
T=nd.arange(100).reshape((3,3,3))
T


[[[ 0.  1.  2.]
  [ 3.  4.  5.]
  [ 6.  7.  8.]]

 [[ 9. 10. 11.]
  [12. 13. 14.]
  [15. 16. 17.]]

 [[18. 19. 20.]
  [21. 22. 23.]
  [24. 25. 26.]]]
<NDArray 3x3x3 @cpu(0)>

In [39]:
T[1,2,1],T[1,2,:],T[1,:,:]

(
 [16.]
 <NDArray 1 @cpu(0)>,
 
 [15. 16. 17.]
 <NDArray 3 @cpu(0)>,
 
 [[ 9. 10. 11.]
  [12. 13. 14.]
  [15. 16. 17.]]
 <NDArray 3x3 @cpu(0)>)

In [40]:
#2.2.5运算的内存开销

In [41]:
before =id(Y)
Y=Y+X
id(Y)==before

False

In [42]:
Z=Y.zeros_like()
before=id(Z)
Z[:]=X+Y
id(Z)==before

True

In [43]:
Y.zeros_like(),nd.zeros_like(Y)

(
 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]
 <NDArray 3x4 @cpu(0)>,
 
 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]
 <NDArray 3x4 @cpu(0)>)

In [44]:
nd.elemwise_add(X,Y,out=Z)
id(Z)==before

True

In [45]:
before=id(X)
X+=Y
id(X)==before

True

In [46]:
#2.2.6NDArray和NumPy相互变换

In [47]:
import numpy as np

P=np.ones((2,3))
P

array([[1., 1., 1.],
       [1., 1., 1.]])

In [48]:
D=nd.array(P)
D


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [49]:
D.asnumpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)