In [1]:
# 4.4.1 不含模型参数的⾃定义层
from mxnet import gluon,nd
from mxnet.gluon import nn

class CenteredLayer(nn.Block):
    def __init__(self,**kwargs):
        super(CenteredLayer,self).__init__(**kwargs)
        
    def forward(self,x):
        return x-x.mean()

In [2]:
layer=CenteredLayer()
layer(nd.array([1,2,3,4,5]))


[-2. -1.  0.  1.  2.]
<NDArray 5 @cpu(0)>

In [3]:
net=nn.Sequential()
net.add(nn.Dense(128),
       CenteredLayer())

In [4]:
net.initialize()
y=net(nd.random.uniform(shape=(4,8)))
y.mean().asscalar()

-9.367795e-10

In [5]:
# 4.4.2 含模型参数的⾃定义层 
params=gluon.ParameterDict()
# get在params这个参数字典(ParameterDict类型)中查找'param2'，
# 若未找到则创建键值对(key='param2',value为parameter类型)
params.get('param2',shape=(2,3))
type(params)

mxnet.gluon.parameter.ParameterDict

In [6]:
class MyDense(nn.Block):
    # units为该层的输出个数，in_units为该层的输入个数
    def __init__(self,units,in_units,**kwargs):
        super(MyDense,self).__init__(**kwargs)
        self.weight=self.params.get('weight',shape=(in_units,units))
        self.bias=self.params.get('bias',shape=(units,))
        
    def forward(self,x):
        linear=nd.dot(x,self.weight.data())+self.bias.data()
        return nd.relu(linear)

In [7]:
dense=MyDense(units=3,in_units=5)
dense.params

mydense0_ (
  Parameter mydense0_weight (shape=(5, 3), dtype=<class 'numpy.float32'>)
  Parameter mydense0_bias (shape=(3,), dtype=<class 'numpy.float32'>)
)

In [8]:
dense.initialize()
dense(nd.random.uniform(shape=(2,5)))


[[0.06917784 0.01627153 0.01029644]
 [0.02602214 0.04537309 0.        ]]
<NDArray 2x3 @cpu(0)>

In [9]:
net=nn.Sequential()
net.add(MyDense(8,in_units=64),
       MyDense(1,in_units=8))
net.initialize()
net(nd.random.uniform(shape=(2,64)))


[[0.03820475]
 [0.04035058]]
<NDArray 2x1 @cpu(0)>

In [10]:
nn.Block??


from mxnet import init
init.Uniform??
nd.random.uniform??
gluon.parameter.ParameterDict??