In [1]:
# 4.5.1 读写NDArray
# 直接使⽤save函数和load函数分别存储和读取NDArray。
from mxnet import nd
from mxnet.gluon import nn

x=nd.ones(3)
nd.save('x',x)

In [3]:
x2=nd.load('x')
x2

[
 [1. 1. 1.]
 <NDArray 3 @cpu(0)>]

In [12]:
y=nd.zeros(4)
nd.save('xy',[x,y])# 保存NDArray列表为文件
x2,y2=nd.load('xy')# 读取文件里的NDArray
x2,y2

(
 [1. 1. 1.]
 <NDArray 3 @cpu(0)>,
 
 [0. 0. 0. 0.]
 <NDArray 4 @cpu(0)>)

In [15]:
mydict={'x':x,'y':y}
nd.save('mydict',mydict)# 保存str->NDArray的字典为文件
mydict2=nd.load('mydict')
mydict2

{'x': 
 [1. 1. 1.]
 <NDArray 3 @cpu(0)>,
 'y': 
 [0. 0. 0. 0.]
 <NDArray 4 @cpu(0)>}

In [17]:
# 4.5.2 读写Gluon模型的参数
class MLP(nn.Block):
    def __init__(self,**kwargs):
        super(MLP,self).__init__(**kwargs)
        self.hidden=nn.Dense(256,activation='relu')
        self.output=nn.Dense(10)
        
    def forward(self,x):
        return self.output(self.hidden(x))
    
net=MLP()
net.initialize()
X=nd.random.uniform(shape=(2,20))
Y=net(X)

In [22]:
filename='mlp.params'
net.save_parameters(filename)# 保存模型参数为文件

In [23]:
net2=MLP()
net2.load_parameters(filename)# 读取文件里的模型参数

In [26]:
Y2=net2(X)
Y2==Y


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
<NDArray 2x10 @cpu(0)>

In [27]:

nd.save??
nd.load??
nd.save??
nn.Block??

nn.HybridBlock.export??
net.save_parameters??
net.load_parameters??