In [4]:
from mxnet import nd

# 创建NDArray

In [5]:
# 新建一个长度为12的数组，@cpu的意思是，被创建在CPU使用的内存上
# nd.arange这个方法，只能创建一维数组
X = nd.arange(12)
X


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [6]:
# shape属性能够获取NDArray的形状
#(12,)说明他是一维数组
X.shape


(12,)

In [7]:
# 获得实例的总个数
X.size

12

In [8]:
# reshape方法，可以改变ndarray的形状，也就是维度
X = X.reshape(3,4)
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [9]:
# 这里要注意的是，zeros这个方法的参数是一个tuple，返回值是list
nd.zeros((2,3,4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [10]:
# 用法与zeros一样
nd.ones((3,4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [11]:
# 用nd.array创建多维数组
Y = nd.array([
    [2,1,4,3],
    [1,2,3,4],
    [4,3,2,1],
])
Y


[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
<NDArray 3x4 @cpu(0)>

In [12]:
# 随机生成一个数组 ,它的每个元素都随机采样于均值为0、标准差为1的正态分布
nd.random.normal(0,1,shape=(3,4))


[[ 2.2122064   0.7740038   1.0434403   1.1839255 ]
 [ 1.8917114  -1.2347414  -1.771029   -0.45138445]
 [ 0.57938355 -1.856082   -1.9768796  -0.20801921]]
<NDArray 3x4 @cpu(0)>

# 运算
- X = [[ 0.  1.  2.  3.]
       [ 4.  5.  6.  7.]
       [ 8.  9. 10. 11.]]
- Y = [[2. 1. 4. 3.]
       [1. 2. 3. 4.]
       [4. 3. 2. 1.]]

In [13]:
# 加法
X + Y


[[ 2.  2.  6.  6.]
 [ 5.  7.  9. 11.]
 [12. 12. 12. 12.]]
<NDArray 3x4 @cpu(0)>

In [14]:
# 乘法,与矩阵中的乘法不同，这里只是对应元素相乘而已
# 想要像矩阵里面一样相乘，需要用dot方法
X * Y


[[ 0.  1.  8.  9.]
 [ 4. 10. 18. 28.]
 [32. 27. 20. 11.]]
<NDArray 3x4 @cpu(0)>

In [15]:
# 除法，规则是对应元素相除，如果分母是0,则显示inf(infinity无穷的意思)
X / Y


[[ 0.    1.    0.5   1.  ]
 [ 4.    2.5   2.    1.75]
 [ 2.    3.    5.   11.  ]]
<NDArray 3x4 @cpu(0)>

In [17]:
# 指数运算,规则是e^xxx
Y.exp()


[[ 7.389056   2.7182817 54.59815   20.085537 ]
 [ 2.7182817  7.389056  20.085537  54.59815  ]
 [54.59815   20.085537   7.389056   2.7182817]]
<NDArray 3x4 @cpu(0)>

In [20]:
# 矩阵的乘法nd.dot
# 因为X是3×4,Y也是3×4,根据矩阵相乘的规则，X和Y是不能相乘的，因此要将Y或者X转置才行
nd.dot(X,Y.T)
nd.dot(X.T,Y)


[[36. 32. 28. 24.]
 [43. 38. 37. 32.]
 [50. 44. 46. 40.]
 [57. 50. 55. 48.]]
<NDArray 4x4 @cpu(0)>

In [25]:
# concat方法，将两个矩阵连起来，横着竖着都可以，前提是两个矩阵的行或者列相同
# dim = 0 是竖着拼
nd.concat(X, Y, dim = 0),nd.concat(X, Y, dim = 1)

# dim = 1 是横着拼

(
 [[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]
  [ 2.  1.  4.  3.]
  [ 1.  2.  3.  4.]
  [ 4.  3.  2.  1.]]
 <NDArray 6x4 @cpu(0)>,
 
 [[ 0.  1.  2.  3.  2.  1.  4.  3.]
  [ 4.  5.  6.  7.  1.  2.  3.  4.]
  [ 8.  9. 10. 11.  4.  3.  2.  1.]]
 <NDArray 3x8 @cpu(0)>)

In [34]:
# ==:判断两个矩阵的每个元素是否相同，返回一个矩阵，元素为1表示相同，为0表示不同

X == Y

'''
Z = nd.array(
    [
        [1,2,3,4],
        [5,6,7,8],
    ]
)
X == Z 运行这一样是会报错的，这里一定要保证两个比较的矩阵的行列都相同
'''

'\nZ = nd.array(\n    [\n        [1,2,3,4],\n        [5,6,7,8],\n    ]\n)\nX == Z 运行这一样是会报错的，这里一定要保证两个比较的矩阵的行列都相同\n'

In [55]:
# 求和函数sum，计算一个矩阵中所有元素的和
X.sum()
nd.sum(X)


[66.]
<NDArray 1 @cpu(0)>

In [54]:
'''
    norm():it computes the L2 norm on the entire array
    也就是说norm是用来算L2范数的。
    科普一下什么是L0,L1，L2范数
    L0范数：表示矩阵中非0元素的个数
    L1范数：表示矩阵中元素与0之间的曼哈顿距离，也可以理解为所有元素的绝对值的和
    L2范数：表示矩阵中元素与0之间的欧几里得距离，也就是所有元素的平方和的开平方
    还有个LP范数，没看懂，作用是：控制模型复杂度减少过拟合，一般在损失函数中加入惩罚项。
    X = [ 0. 1. 2. 3.]
        [ 4. 5. 6. 7.]
        [ 8. 9.10. 11.]
    我们可以手动算一下X.norm   sqrt(0+1+4+9+16+25+36+49+64+81+100+121) = sqrt(506) = 22.494442跟答案一致
    
    asscalar():将ndarray转换成标量，并且矩阵只能是一维且只有单个元素的向量，其实就是把ndarray类型转换成标量，且向量只有1个元素
    
'''
X.norm()
X.norm().asscalar()
a = nd.array(
    [12]
)
a.asscalar()


12.0

# 广播机制
- 当两个形状不同的NDArray进行运算时，可能会给两个矩阵补成一样的形状


In [63]:
A = nd.arange(3).reshape((3,1))
B = nd.arange(2).reshape((1,2))
A,B

(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>,
 
 [[0. 1.]]
 <NDArray 1x2 @cpu(0)>)

In [71]:
'''
那么如上的A，B显然不同行也不同列，对他们进行运算，会怎么样呢？？
    答案是这个：   [[0. 1.]
                 [1. 2.]
                 [2. 3.]]
通过逆向，我们可以得到  [0 0 ]    [0 1]      [0 1]
                    [1 1]  +  [0 1]    = [1 2]
                    [2 2]     [0 1]      [2 3]
其实他就是用已知的行或者列复制以后凑成相同的矩阵规模

如果是 [0 1]   +  [1, 1, 1]
      [1 2]                  首先确定，最后的矩阵是3×2的
      
      [0 1 x]  + [1 1 1]
      [1 2 x]    [1 1 1]
      
      x处应该是什么呢？ 运行发现报错了0 0，因此只有一行或者一列时才会触发广播，不然程序也不知道要复制哪一行或者列的
      
'''
A + B
'''
C = nd.array([[0,1],[1,2]])
D = nd.array([[1,1,1]])
C + D 报错
将D 改为 D = nd.array([[1,1]]) ，正常！
'''

'\nC = nd.array([[0,1],[1,2]])\nD = nd.array([[1,1,1]])\nC + D 报错\n将D 改为 D = nd.array([[1,1]]) ，正常！\n'

# 索引
- array[start:end]，注意是左闭右开，左边取得到，右边取不到
-     X = [ 0. 1. 2. 3.]
          [ 4. 5. 6. 7.]
          [ 8. 9.10. 11.]

In [119]:
# 截取行索引
X[1:3]
# 那么怎么截取列索引？？
# 1.在截取行索引的情况下，2.再截取列索引
# 这里我想截取整个矩阵的0,1列
X[:,[0,2]]



# 这里我想截取第0,1行的，0,1列
# 1.截取0,1行
p = X[0:2]
# 2.截取0,1列
q = p[:,[0,2]]

# 简化一下
X[0:2][:,[0,2]]



[[ 4. 18.]
 [22. 51.]]
<NDArray 2x2 @cpu(0)>

In [75]:
# 重新赋值
# 将X矩阵的第1行，第2列置为9
X[1,2] = 9
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  9.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

# 运算的内存开销
- 我们可以通过id来查看，两个实例是不是指向同一块内存，如果是，则相等，否则不等

In [77]:
before = id(Y)
Y = Y + X
id(Y) == before
# 这里就说明了，当执行加法时，重新开辟了一块内存给新的Y存放

False

In [86]:
Z = nd.zeros_like(Y) #创建与Y形状的相同，所有元素都为0的数组
before = id(Z)

'''
Z[:] = X + Y 的实质其实是，Z原本放在内存A上，X + Y 的结果存到一块新内存B上，通过Z[:]这种方式，把B上的数据又重新放回到A上，
其实还是有临时内存开销的
'''
Z[:] = X + Y
id(Z) == before

True

In [88]:
# 想要避免使用临时内存开销的话，我们可以使用elemwise_add
nd.elemwise_add(X, Y, out=Z)
id(Z) == before

True

In [90]:
before = id(X)
X += Y  # 这里X += Y  和 X[:] = X + Y 是一样的
id(X) == before

True

# NDArray 和 NumPy相互变换

In [91]:
import numpy as np
# numpy 转 ndarray
p = np.ones((2,3))
d = nd.array(p)
d


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [92]:
# ndarray 转 numpy
d.asnumpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

# 练习

In [95]:
# 对应元素，若X上的大于Y上的，则返回1,否则返回0,整个返回一个数组
X > Y


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [98]:
# 将广播机制中按元素运行的两个NDArray替换成其他形状，结果是否和预期一样？
# 答：不一样，上面已经测试过了，如果不是单行或者单列的向量，补齐的时候会报错

# 总结
- nd.arange(n)：创建一个大小为n的一维数组
- nd.reshape()：更改ndarray的形状，注意给的参数必须是tuple的类型
- nd.array()：自定义一个矩阵
- nd.zeros()：创建一个所有元素都为0的矩阵，参数必须是tuple类型
- nd.concat(A,B,dim):拼接两个矩阵的方法，A和B分别表示需要拼接在一起的矩阵，dim表示是横着拼(dim=1)还是竖着拼(dim=0)
- nd.random.normal(a,b,shape=(3,4))随机生成一个数组 ,它的每个元素都随机采样于均值为a、标准差为b的正态分布
- 运算就+,-,×，/，注意都是对应元素之间的运算，还有指数运算，nd.exp(X);如果是想跟矩阵相乘一样，需要使用nd.dot(X,Y)
- 广播机制：必须是行向量或者列向量才能进行补全
- 截取某几行，或者某几列：
    - 单纯截取某些行：X[start,end]，从start行到第end-1行
    - 截取a到b-1行之间,c到d-1列的矩阵：X[a:b][:,[c:d]]
- 运算是减少内存开销的方法：elemwise_add/div/...
        - eg: elemwise_add(X, Y, out=Z) 将X + Y的值赋给Z

- ndarray转numpy：asnumpy()方法
    - eg: X(ndarray类型) X = X.asnumpy()
- numpy转ndarray：array()方法
    - eg: Y(numpy类型) Y = nd.array(Y)
