In [34]:
from mxnet import nd

In [35]:
x = nd.arange(12)

In [36]:
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [37]:
x.shape

(12,)

In [38]:
x.size

12

In [39]:
X = x.reshape((3,4))

In [40]:
X



[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [41]:
nd.zeros((2,3,4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [42]:
nd.ones((3,4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [43]:
import mxnet as mx

In [44]:
Y = nd.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
Y


[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
<NDArray 3x4 @cpu(0)>

In [45]:
nd.random.normal(0,1,shape=(3,4),ctx=mx.gpu())


[[-0.17739409  0.8909654   0.720208   -0.04110664]
 [-0.14618981 -1.1971692   0.48786253 -0.36545533]
 [ 0.48647016 -1.1397052  -2.0556722   1.5083628 ]]
<NDArray 3x4 @gpu(0)>

In [46]:
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [47]:
Y


[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
<NDArray 3x4 @cpu(0)>

In [48]:
X+Y


[[ 2.  2.  6.  6.]
 [ 5.  7.  9. 11.]
 [12. 12. 12. 12.]]
<NDArray 3x4 @cpu(0)>

In [49]:
X*Y


[[ 0.  1.  8.  9.]
 [ 4. 10. 18. 28.]
 [32. 27. 20. 11.]]
<NDArray 3x4 @cpu(0)>

In [50]:
X/Y


[[ 0.    1.    0.5   1.  ]
 [ 4.    2.5   2.    1.75]
 [ 2.    3.    5.   11.  ]]
<NDArray 3x4 @cpu(0)>

In [51]:
Y.exp()


[[ 7.389056   2.7182817 54.59815   20.085537 ]
 [ 2.7182817  7.389056  20.085537  54.59815  ]
 [54.59815   20.085537   7.389056   2.7182817]]
<NDArray 3x4 @cpu(0)>

In [52]:
nd.dot(X,Y.T)


[[ 18.  20.  10.]
 [ 58.  60.  50.]
 [ 98. 100.  90.]]
<NDArray 3x3 @cpu(0)>

In [53]:
nd.concat(X, Y, dim=0), nd.concat(X, Y, dim=1)

(
 [[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]
  [ 2.  1.  4.  3.]
  [ 1.  2.  3.  4.]
  [ 4.  3.  2.  1.]]
 <NDArray 6x4 @cpu(0)>,
 
 [[ 0.  1.  2.  3.  2.  1.  4.  3.]
  [ 4.  5.  6.  7.  1.  2.  3.  4.]
  [ 8.  9. 10. 11.  4.  3.  2.  1.]]
 <NDArray 3x8 @cpu(0)>)

In [54]:
X==Y


[[0. 1. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [55]:
X.sum()


[66.]
<NDArray 1 @cpu(0)>

In [56]:
nd.array([[1,2,2,1]]).norm()


[3.1622777]
<NDArray 1 @cpu(0)>

In [57]:
A = nd.arange(6).reshape((3,1))
B = nd.arange(12).reshape((3,4))
A,B

(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>,
 
 [[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]
 <NDArray 3x4 @cpu(0)>)

In [58]:
A + B


[[ 0.  1.  2.  3.]
 [ 5.  6.  7.  8.]
 [10. 11. 12. 13.]]
<NDArray 3x4 @cpu(0)>

In [59]:
C=B.reshape((2,3,2))
C


[[[ 0.  1.]
  [ 2.  3.]
  [ 4.  5.]]

 [[ 6.  7.]
  [ 8.  9.]
  [10. 11.]]]
<NDArray 2x3x2 @cpu(0)>

In [60]:
C[1,1,1]


[9.]
<NDArray 1 @cpu(0)>

In [61]:
C[1,0:2]=0
C


[[[ 0.  1.]
  [ 2.  3.]
  [ 4.  5.]]

 [[ 0.  0.]
  [ 0.  0.]
  [10. 11.]]]
<NDArray 2x3x2 @cpu(0)>

In [62]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [63]:
Z = Y.zeros_like()
before = id(Z)
Z[:]= X+Y
id(Z)==before

True

In [64]:
nd.elemwise_add(X,Y,out=Z)
id(Z) == before

True

In [65]:
import numpy as np

P = np.ones((2,3))
D = nd.array(P)
D,D.asnumpy()

(
 [[1. 1. 1.]
  [1. 1. 1.]]
 <NDArray 2x3 @cpu(0)>,
 array([[1., 1., 1.],
        [1., 1., 1.]], dtype=float32))

In [68]:
X,Y

(
 [[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]
 <NDArray 3x4 @cpu(0)>,
 
 [[ 2.  2.  6.  6.]
  [ 5.  7.  9. 11.]
  [12. 12. 12. 12.]]
 <NDArray 3x4 @cpu(0)>)

In [69]:
X>Y


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>