In [9]:
from mxnet import nd    #引入mxnet库
x = nd.arange(12)       #创建一个从0开始的12个连续整数  
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [5]:
x.shape                #获取形状，即几行几列

(12,)

In [6]:
x.size                #获取元素个数

12

In [8]:
x.reshape((3,4))      #修改形状为3行4列


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [11]:
nd.zeros((2,3,4))    #生成元素全为0的指定形状的张量


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [3]:
nd.random.normal(0,1,shape=(2,3))         #生成元素都随机采样于均值为0，标准差为1的正态分布，形状为（2,3）


[[ 1.1630785   0.4838046   0.29956347]
 [ 0.15302546 -1.1688148   1.5580711 ]]
<NDArray 2x3 @cpu(0)>

In [4]:
y = nd.array([[2,1,4,3],[1,2,3,4],[4,3,2,1]])   #利用python中的列表创建张量
y


[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
<NDArray 3x4 @cpu(0)>

In [5]:
nd.ones((3,4))     #生成元素全为1的指定形状的张量


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [7]:
z = x.reshape((3,4))
z


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [8]:
z + y                #形状相同的张量按对应元素相加


[[ 2.  2.  6.  6.]
 [ 5.  7.  9. 11.]
 [12. 12. 12. 12.]]
<NDArray 3x4 @cpu(0)>

In [28]:
z * y                #形状相同的张量按对应元素相乘


[[ 0.  1.  8.  9.]
 [ 4. 10. 18. 28.]
 [32. 27. 20. 11.]]
<NDArray 3x4 @cpu(0)>

In [ ]:
z / y                #形状相同的张量按对应元素相除

In [ ]:
z.exp              #指数运算

In [ ]:
x.sum()        #张量的所有元素求和

In [6]:
A = nd.arange(3).reshape((3,1))
B = nd.arange(2).reshape((1,2))
A,B

(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>, 
 [[0. 1.]]
 <NDArray 1x2 @cpu(0)>)

In [7]:
A+B                     #触发广播机制，自动复制补全


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

In [11]:
z[1:3]


[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @cpu(0)>

In [12]:
import numpy as np          #numpy和ndarray的相互转换
P = np.ones((2,3))
D = nd.array(P)
P,D

(array([[1., 1., 1.],
        [1., 1., 1.]]), 
 [[1. 1. 1.]
  [1. 1. 1.]]
 <NDArray 2x3 @cpu(0)>)

In [13]:
D.asnumpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [16]:
z == y       


[[0. 1. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>