**Tensor常见操作**

In [1]:
import torch as t

In [3]:
a = t.arange(0, 6)
a.view(2, 3)

tensor([[0, 1, 2],
        [3, 4, 5]])

In [21]:
b = a.view(-1, 3) # 当某一维为-1的时候，会自动计算它的大小
b.shape

torch.Size([2, 3])

In [25]:
b.unsqueeze(1) # 注意形状，在第2维（下标从0开始）上增加“１” 

tensor([[[0, 1, 2]],

        [[3, 4, 5]]])

In [28]:
b.unsqueeze(1).shape

torch.Size([2, 1, 3])

In [29]:
b.resize_(1,3)       # 数据仍得到保留

tensor([[0, 1, 2]])

In [31]:
b.resize_(3,3)        #

tensor([[                0,                 1,                 2],
        [                3,                 4,                 5],
        [27303532308922465, 25896191785238631, 27866512327901300]])

**索引操作**

In [32]:
a = t.randn(3, 4)
a

tensor([[ 0.8448,  1.7335,  0.3403,  0.9039],
        [ 2.5822,  0.9394,  0.0062,  1.4326],
        [-0.8812,  0.0823, -0.6551,  1.5819]])

In [33]:
a[0] # 第0行(下标从0开始)

tensor([0.8448, 1.7335, 0.3403, 0.9039])

In [34]:
a[:, 0] # 第0列

tensor([ 0.8448,  2.5822, -0.8812])

In [35]:
a[0][2] # 第0行第2个元素，等价于a[0, 2]

tensor(0.3403)

In [36]:
a[0, -1] # 第0行最后一个元素

tensor(0.9039)

In [37]:
a[0, 2] # 等价于a[0][2]

tensor(0.3403)

In [38]:
a[:2] # 前两行

tensor([[0.8448, 1.7335, 0.3403, 0.9039],
        [2.5822, 0.9394, 0.0062, 1.4326]])

In [40]:
a[:2, 0:2] # 前两行，第0,1列

tensor([[0.8448, 1.7335],
        [2.5822, 0.9394]])

In [41]:
print(a[0:1, :2]) # 第0行，前两列 
print(a[0, :2]) # 注意两者的区别：形状不同

tensor([[0.8448, 1.7335]])
tensor([0.8448, 1.7335])


In [42]:
# None类似于np.newaxis, 为a新增了一个轴
# 等价于a.view(1, a.shape[0], a.shape[1])
a[None].shape

torch.Size([1, 3, 4])

In [43]:
a[:,None,:].shape

torch.Size([3, 1, 4])

In [44]:
a[:,None,:,None,None].shape

torch.Size([3, 1, 4, 1, 1])

In [45]:
a > 1 # 返回一个ByteTensor

tensor([[False,  True, False, False],
        [ True, False, False,  True],
        [False, False, False,  True]])

In [46]:
a[a>1] # 等价于a.masked_select(a>1)
# 选择结果与原tensor不共享内存空间

tensor([1.7335, 2.5822, 1.4326, 1.5819])

In [47]:
a[0,0] #依旧是tensor）

tensor(0.8448)

In [48]:
a[0,0].item() # python float

0.8448254466056824

In [49]:
d = a[0:1, 0:1, None]
print(d.shape)
d.item() # 只包含一个元素的tensor即可调用tensor.item,与形状无关

torch.Size([1, 1, 1])


0.8448254466056824

**高级索引**
高级索引操作的结果一般不和原始的Tensor共享内存,对多个数据进行索引时,将行索引放一起,列索引放一起.

In [50]:
x = t.arange(0,27).view(3,3,3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

In [51]:
x[[1, 2], [1, 2], [2, 0]] # x[1,1,2]和x[2,2,0]

tensor([14, 24])

In [52]:
x[[2, 1, 0], [0], [1]] # x[2,0,1],x[1,0,1],x[0,0,1]

tensor([19, 10,  1])

In [55]:
x[[0, 2], ...] # x[0] 和 x[2]

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

In [56]:
x[[0, 2], [1,0],...] # x[0][1] 和 x[2][0]

SyntaxError: invalid syntax (<ipython-input-56-85689f26a8d2>, line 1)