**逐元素操作**

In [1]:
import torch as t

In [2]:
a = t.arange(0, 6).view(2, 3).float()
t.cos(a) # 矩阵中的每一个元素都进行cos操作

tensor([[ 1.0000,  0.5403, -0.4161],
        [-0.9900, -0.6536,  0.2837]])

In [3]:
a % 3 # 等价于t.fmod(a, 3)

tensor([[0., 1., 2.],
        [0., 1., 2.]])

In [4]:
# 取a中的每一个元素与3相比较大的一个 (小于3的截断成3)
print(a)
t.clamp(a, min=3)

tensor([[0., 1., 2.],
        [3., 4., 5.]])


tensor([[3., 3., 3.],
        [3., 4., 5.]])

In [5]:
b = a.sin_() # 效果同 a = a.sin();b=a ,但是更高效节省显存
a

tensor([[ 0.0000,  0.8415,  0.9093],
        [ 0.1411, -0.7568, -0.9589]])

In [6]:
b = t.ones(2, 3)
b.sum(dim = 0, keepdim=True)

tensor([[2., 2., 2.]])

In [7]:
# keepdim=False，不保留维度"1"，注意形状
b.sum(dim=0, keepdim=False)

tensor([2., 2., 2.])

In [8]:
b.sum(dim=1)

tensor([3., 3.])

In [9]:
a = t.arange(0, 6).view(2, 3)
print(a)
a.cumsum(dim=1) # 沿着行累加

tensor([[0, 1, 2],
        [3, 4, 5]])


tensor([[ 0,  1,  3],
        [ 3,  7, 12]])

In [10]:
a = t.linspace(0, 15, 6).view(2, 3)
a

tensor([[ 0.,  3.,  6.],
        [ 9., 12., 15.]])

In [11]:
b = t.linspace(15, 0, 6).view(2, 3)
b

tensor([[15., 12.,  9.],
        [ 6.,  3.,  0.]])

In [12]:
a>b

tensor([[False, False, False],
        [ True,  True,  True]])

In [13]:
a[a>b] # a中大于b的元素

tensor([ 9., 12., 15.])

In [14]:
t.max(a)   # 选择出a中最大的数值

tensor(15.)

In [15]:
t.max(b, dim=1) 
# 第一个返回值的15和6分别表示第0行和第1行最大的元素
# 第二个返回值的0和0表示上述最大的数是该行第0个元素

torch.return_types.max(
values=tensor([15.,  6.]),
indices=tensor([0, 0]))

In [16]:
t.max(a,b)

tensor([[15., 12.,  9.],
        [ 9., 12., 15.]])

In [17]:
# 比较a和10较大的元素，并保留较大的元素
t.clamp(a, min=10)

tensor([[10., 10., 10.],
        [10., 12., 15.]])

In [18]:
t.sort(a) # 第一个返回排序状态，第二个返回下标

torch.return_types.sort(
values=tensor([[ 0.,  3.,  6.],
        [ 9., 12., 15.]]),
indices=tensor([[0, 1, 2],
        [0, 1, 2]]))

In [19]:
sorts , indices = t.sort(a)
print(sorts,indices)

tensor([[ 0.,  3.,  6.],
        [ 9., 12., 15.]]) tensor([[0, 1, 2],
        [0, 1, 2]])


**线性代数**

In [20]:
b = a.t()
b.is_contiguous()    # 判断存储空间是否连续

False

In [21]:
b.contiguous()

tensor([[ 0.,  9.],
        [ 3., 12.],
        [ 6., 15.]])

In [22]:
b.diag()   # 对角线元素

tensor([ 0., 12.])