In [1]:
import numpy as np
import torch as t

In [2]:
a = np.ones([2, 3],dtype=np.float32)
a

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [3]:
b = t.from_numpy(a) # numpy转换为tensor
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [4]:
a[0, 1]=100
b

tensor([[  1., 100.,   1.],
        [  1.,   1.,   1.]])

In [5]:
c = b.numpy() # a, b, c三个对象共享内存
c  # tensor转换为numpy

array([[  1., 100.,   1.],
       [  1.,   1.,   1.]], dtype=float32)