In [1]:
import torch as t

In [18]:
a = t.arange(0, 6)
a,a.storage()

(tensor([0, 1, 2, 3, 4, 5]),
  0
  1
  2
  3
  4
  5
 [torch.LongStorage of size 6])

In [19]:
b = a.view(2, 3)
b.storage()

 0
 1
 2
 3
 4
 5
[torch.LongStorage of size 6]

In [20]:
# 一个对象的id值可以看作它在内存中的地址
# storage的内存地址一样，即是同一个storage
id(b.storage()) == id(a.storage())

True

In [21]:
# a改变，b也随之改变，因为他们共享storage
a[1] = 100
b

tensor([[  0, 100,   2],
        [  3,   4,   5]])

In [22]:
c = a[2:] 
c,c.storage()

(tensor([2, 3, 4, 5]),
  0
  100
  2
  3
  4
  5
 [torch.LongStorage of size 6])

In [23]:
c.data_ptr(), a.data_ptr() # data_ptr返回tensor首元素的内存地址


(2433019578448, 2433019578432)

In [25]:
c[0] = -100 # c[0]的内存地址对应a[2]的内存地址
a,c

(tensor([   0,  100, -100,    3,    4,    5]),
 tensor([-100,    3,    4,    5]))

In [28]:
d = t.LongTensor(c.storage())
d[0] = 6666
b,d,c

(tensor([[6666,  100, -100],
         [   3,    4,    5]]),
 tensor([6666,  100, -100,    3,    4,    5]),
 tensor([-100,    3,    4,    5]))

In [12]:
# 下面４个tensor共享storage
id(a.storage()) == id(b.storage()) == id(c.storage()) == id(d.storage())

True

In [14]:
# 获取首元素相对于storage地址的偏移量
a.storage_offset(), c.storage_offset(), d.storage_offset(),b.storage_offset()

(0, 2, 0, 0)

In [29]:
e = b[::2, ::2] # 隔2行/列取一个元素
id(e.storage()) == id(a.storage())

True

In [31]:
b,e,b.stride(), e.stride()

(tensor([[6666,  100, -100],
         [   3,    4,    5]]),
 tensor([[6666, -100]]),
 (3, 1),
 (6, 2))

In [32]:
e.is_contiguous()

False

In [34]:
e.storage()

 6666
 100
 -100
 3
 4
 5
[torch.LongStorage of size 6]

**其他**