In [11]:
# 池化层的前向计算实现在pool2d函数⾥。
from mxnet import nd
from mxnet.gluon import nn

def pool2d(X,pool_size,mode='max'):
    p_h,p_w=pool_size
    Y=nd.zeros( (X.shape[0]-p_h+1,X.shape[1]-p_w+1) )# 输出数组2x2
    for i in range(Y.shape[0]):# 池化窗口按行滚动
        for j in range(Y.shape[1]):# 按列滚动
            if mode=='max':
                Y[i,j]=X[i:i+p_h,j:j+p_w].max()
            elif mode=='avg':
                Y[i,j]=X[i:i+p_h,j:j+p_w].mean()
    return Y

In [18]:
X=nd.array([ [0,1,2],[3,4,5],[6,7,8] ])
pool2d(X,(2,2))


[[4. 5.]
 [7. 8.]]
<NDArray 2x2 @cpu(0)>

In [15]:
pool2d(X,(2,2),'avg')


[[2. 3.]
 [5. 6.]]
<NDArray 2x2 @cpu(0)>

In [25]:
# 5.4.2 填充和步幅 
# 同卷积层⼀样，池化层也可以在输⼊的⾼和宽两侧的填充并调整窗口的移动步幅来改变输出形状。
X=nd.arange(16).reshape((1,1,4,4))# 前两个维度分别是批量和通道
X


[[[[ 0.  1.  2.  3.]
   [ 4.  5.  6.  7.]
   [ 8.  9. 10. 11.]
   [12. 13. 14. 15.]]]]
<NDArray 1x1x4x4 @cpu(0)>

In [26]:
# 默认情况下，MaxPool2D实例⾥步幅和池化窗口形状相同(3x3)。
pool2d=nn.MaxPool2D(3)
pool2d(X) # 因为池化层没有模型参数，所以不需要调⽤参数初始化函数


[[[[10.]]]]
<NDArray 1x1x1x1 @cpu(0)>

In [30]:
# ⼿动指定步幅和填充。 
pool2d=nn.MaxPool2D(3,padding=1,strides=2)# (n-k+p+s)/s即(4-3+2+2)/2
pool2d(X)


[[[[ 5.  7.]
   [13. 15.]]]]
<NDArray 1x1x2x2 @cpu(0)>

In [35]:
# 以指定⾮正⽅形的池化窗口，并分别指定⾼和宽上的填充和步幅。 
pool2d=nn.MaxPool2D((2,3),padding=(1,2),strides=(2,3))
pool2d(X)


[[[[ 0.  3.]
   [ 8. 11.]
   [12. 15.]]]]
<NDArray 1x1x3x2 @cpu(0)>

In [64]:
# 5.4.3 多通道 
# 在处理多通道输⼊数据时，池化层对每个输⼊通道分别池化，而不是像卷积层那样将各通道的输⼊按通道相加。
# 这意味着池化层的输出通道数与输⼊通道数相等。
# nd.concat沿着连接轴的输出数组的尺寸将等于输入数组的相应维度(dim)的总和。
X=nd.concat(X,X+1,dim=1)# 通道数变为2
X


[[[[ 0.  1.  2.  3.]
   [ 4.  5.  6.  7.]
   [ 8.  9. 10. 11.]
   [12. 13. 14. 15.]]

  [[ 1.  2.  3.  4.]
   [ 5.  6.  7.  8.]
   [ 9. 10. 11. 12.]
   [13. 14. 15. 16.]]]]
<NDArray 1x2x4x4 @cpu(0)>

In [76]:
pool2d=nn.MaxPool2D(3,padding=1,strides=2)
pool2d(X)# 池化后，输出通道数仍然是2。


[[[[ 5.  7.]
   [13. 15.]]

  [[ 6.  8.]
   [14. 16.]]]]
<NDArray 1x2x2x2 @cpu(0)>

In [32]:
nn.MaxPool2D??

In [63]:
nd.reshape??
nn.Conv2D??
nd.concat??
nd.stack??