In [87]:
import torch

# 我们创建一个张量并设置 requires_grad=True 用来追踪他的计算历史：
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [88]:
# 对张量进行操作，也就是计算过程：
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [89]:
y.grad_fn

In [90]:
z = y * y * 3
out = z.sum()

z, out

(tensor([[27., 27.],
         [27., 27.]], grad_fn=<MulBackward0>),
 tensor(108., grad_fn=<SumBackward0>))

In [91]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [92]:
out.backward()

In [93]:
print(x.grad)

tensor([[36., 36.],
        [36., 36.]])


In [56]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

y

tensor([  -28.3163,   697.8836, -1304.7695], grad_fn=<MulBackward0>)

In [57]:
# 常规是对标量1进行反向传播，也可以自己进行指定，相应要乘以指定的值
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(gradients)

x.grad

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])

In [58]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [66]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
