In [25]:
import torch
# 构造一个5*3的矩阵，不初始化
x = torch.empty(5,3)
x

tensor([[9.2755e-39, 1.0561e-38, 3.5736e+09],
        [2.6728e+09, 4.2246e-39, 1.0286e-38],
        [1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39],
        [8.7245e-39, 9.2755e-39, 8.9082e-39]])

In [2]:
# 构造一个随机初始化的矩阵
x = torch.rand(5,3)

tensor([[0.7063, 0.8622, 0.0818],
        [0.9791, 0.6920, 0.1087],
        [0.1129, 0.7858, 0.3963],
        [0.7886, 0.5503, 0.8329],
        [0.6777, 0.8511, 0.1523]])

In [3]:
# 构造一个全是0的矩阵，数据类型为long
x = torch.zeros((5,3),dtype = torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [4]:
# 直接通过列表来构建张量
x = torch.tensor([1,2,3,4])
x

tensor([1, 2, 3, 4])

In [8]:
# 通过一个tensor创建新的tensor
x = x.new_ones(5,3,dtype = torch.long)
y = torch.randn_like(x,dtype = torch.float)
print(x,y)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]) tensor([[ 0.5083,  0.9017,  1.7215],
        [ 0.2937, -1.2521, -0.6918],
        [ 0.0982, -1.6868, -0.5215],
        [-1.4099,  0.6482, -0.3798],
        [ 0.7287,  0.0430,  1.6389]])


In [9]:
# 获取维度信息
x.size()

torch.Size([5, 3])

In [10]:
# tensor的加法1
x + y

tensor([[ 1.5083,  1.9017,  2.7215],
        [ 1.2937, -0.2521,  0.3082],
        [ 1.0982, -0.6868,  0.4785],
        [-0.4099,  1.6482,  0.6202],
        [ 1.7287,  1.0430,  2.6389]])

In [11]:
# tensor的加法2
torch.add(x,y)

tensor([[ 1.5083,  1.9017,  2.7215],
        [ 1.2937, -0.2521,  0.3082],
        [ 1.0982, -0.6868,  0.4785],
        [-0.4099,  1.6482,  0.6202],
        [ 1.7287,  1.0430,  2.6389]])

In [12]:
# 提供一个输出tensor位置参数
res = torch.empty(x.size())
# res接收加法运算的结果
torch.add(x,y,out = res)
res

tensor([[ 1.5083,  1.9017,  2.7215],
        [ 1.2937, -0.2521,  0.3082],
        [ 1.0982, -0.6868,  0.4785],
        [-0.4099,  1.6482,  0.6202],
        [ 1.7287,  1.0430,  2.6389]])

In [13]:
# tensor的加法3  内联函数
y.add_(x)
y

tensor([[ 1.5083,  1.9017,  2.7215],
        [ 1.2937, -0.2521,  0.3082],
        [ 1.0982, -0.6868,  0.4785],
        [-0.4099,  1.6482,  0.6202],
        [ 1.7287,  1.0430,  2.6389]])

In [14]:
# 使用索引操作
x[:,1]

tensor([1, 1, 1, 1, 1])

In [15]:
# 使用torch.view改变tensor的形状
x = torch.randn(4,4)
y = x.view(1,16)
z = x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([1, 16]) torch.Size([2, 8])


In [23]:
# 通过.item来获得tensor的value
x = torch.tensor([2,3])
i = x[1].item()
i

3

In [27]:
# 将 PyTorch 张量转换为 NumPy 数组：
a = torch.ones(5)
b = a.numpy()
print(a,b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]


In [28]:
a.add_(1)
print(a,b)

tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [29]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
a, b

(array([2., 2., 2., 2., 2.]),
 tensor([2., 2., 2., 2., 2.], dtype=torch.float64))